const WeatherConditions = {
    Rain: {
      color: '#005BEA',
      title: 'Raining',
      subtitle: 'Get a cup of coffee',
      icon: 'weather-rainy',
      iconColor: '#3498db',
    },
    Sunny: {
      color: '#FFD300',
      title: 'Sunny',
      subtitle: 'Enjoy the sunshine',
      icon: 'weather-sunny',
      iconColor: '#f1c40f',
    },
    Clear: {
      color: '#FF5733',
      title: 'Clear Sky',
      subtitle: 'Perfect day for outdoor activities',
      icon: 'weather-sunny',
      iconColor: '#e74c3c',
    },
    Thunderstorm: {
      color: '#616161',
      title: 'Thunderstorm',
      subtitle: "Stay indoors, it's stormy",
      icon: 'weather-lightning',
      iconColor: '#34495e',
    },
    Clouds: {
      color: '#1F1C2C',
      title: 'Cloudy',
      subtitle: 'Partly cloudy day',
      icon: 'weather-cloudy',
      iconColor: '#34495e',
    },
    Snow: {
      color: '#00d2ff',
      title: 'Snow',
      subtitle: 'Time to build a snowman!',
      icon: 'weather-snowy',
      iconColor: '#00b0ff',
    },
    Drizzle: {
      color: '#076585',
      title: 'Drizzle',
      subtitle: 'Light rain, grab an umbrella',
      icon: 'weather-hail',
      iconColor: '#2e86de',
    },
    Haze: {
      color: '#66A6FF',
      title: 'Haze',
      subtitle: 'Hazy weather, take precautions',
      icon: 'weather-hail',
      iconColor: '#82ccdd',
    },
    Mist: {
      color: '#8F8F8F',
      title: 'Mist',
      subtitle: "Low visibility, be cautious",
      icon: 'weather-fog',
      iconColor: '#95a5a6',
    },
    Tornado: {
      color: '#1A1A1A',
      title: 'Tornado',
      subtitle: 'Seek shelter immediately',
      icon: 'weather-tornado',
      iconColor: '#2c3e50',
    },
    Sandstorm: {
      color: '#FFC300',
      title: 'Sandstorm',
      subtitle: 'Protect your eyes and face',
      icon: 'weather-windy',
      iconColor: '#e67e22',
    },
    Smoke: {
      color: '#7E7E7E',
      title: 'Smoke',
      subtitle: 'Poor air quality, stay indoors',
      icon: 'weather-fog',
      iconColor: '#95a5a6',
    },
    Windy: {
      color: '#95A5A6',
      title: 'Windy',
      subtitle: 'Hold on to your hat!',
      icon: 'weather-windy',
      iconColor: '#34495e',
    },
    Hail: {
      color: '#95A5A6',
      title: 'Hailstorm',
      subtitle: 'Beware of falling ice',
      icon: 'weather-hail',
      iconColor: '#34495e',
    },
    Dust: {
      color: '#9E9E9E',
      title: 'Dust Storm',
      subtitle: 'Visibility is low',
      icon: 'weather-fog',
      iconColor: '#95a5a6',
    },
    Foggy: {
      color: '#A2A2A2',
      title: 'Foggy',
      subtitle: 'Drive carefully',
      icon: 'weather-fog',
      iconColor: '#95a5a6',
    },
    Blizzard: {
      color: '#85A5D9',
      title: 'Blizzard',
      subtitle: 'Stay indoors and warm',
      icon: 'weather-snowy',
      iconColor: '#7f8c8d',
    },
    TropStorm: {
      color: '#7580E9',
      title: 'Tropical Storm',
      subtitle: 'Prepare for heavy rain',
      icon: 'weather-stormy',
      iconColor: '#5d6d7e',
    },
    Hurricane: {
      color: '#505050',
      title: 'Hurricane',
      subtitle: 'Stay safe and evacuate',
      icon: 'weather-stormy',
      iconColor: '#34495e',
    },
    Fog: {
      color: '#C4C4C4',
      title: 'Fog',
      subtitle: 'Low visibility, drive safely',
      icon: 'weather-fog',
      iconColor: '#95a5a6',
    },
    Rainbow: {
      color: '#FF6D00',
      title: 'Rainbow',
      subtitle: "Nature's beauty after rain",
      icon: 'weather-rainbow',
      iconColor: '#e67e22',
    },
    Volcano: {
      color: '#D40000',
      title: 'Volcanic Ash',
      subtitle: 'Air quality is hazardous',
      icon: 'weather-fog',
      iconColor: '#95a5a6',
    },
    Alien: {
      color: '#32CD32',
      title: 'Alien Weather',
      subtitle: 'Prepare for the unknown',
      icon: 'alien-outline',
      iconColor: '#27ae60',
    },
  };
  
  export default WeatherConditions;
  